#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$input = new \Symfony\Component\Console\Input\ArgvInput();

$application = new \Symfony\Component\Console\Application();
$application->add(new \Kix\PhpstanUtils\Command\CollectCommand());

$application->run($input);